services:
  backend:
    build: ./docker/backend
    container_name: smuggling-backend
    expose:
      - "3000"

  nginx:
    build: ./docker/nginx
    container_name: smuggling-nginx
    expose:
      - "8000"
    depends_on:
      - backend

  haproxy-1x:
    build: ./docker/haproxy-1.8
    container_name: smuggling-haproxy-1x
    ports:
      - "6000:6000"
    depends_on:
      - nginx

  haproxy-2x:
    build: ./docker/haproxy-2x
    container_name: smuggling-haproxy-2x
    ports:
      - "6500:6500"
    depends_on:
      - nginx

  ats-8:
    build: ./docker/ats-8
    container_name: smuggling-ats-8
    ports:
      - "6100:6100"
    depends_on:
      - nginx

  ats-9:
    build: ./docker/ats-9
    container_name: smuggling-ats-9
    ports:
      - "6200:6200"
    depends_on:
      - nginx
