events {}
http {
    log_format smuggle '=== NGINX === $remote_addr | $request '
                       '| CL=$content_length TE=$http_transfer_encoding '
                       '| host=$host | conn=$connection';
    access_log /var/log/nginx/access.log smuggle;

    upstream backend {
        server backend:3000;
        keepalive 64;
    }

    server {
        listen 8000;
        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_request_buffering off;
            proxy_buffering off;
            proxy_set_header Transfer-Encoding $http_transfer_encoding;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
        }
    }
}
