events {}

http {
    log_format smuggle '$remote_addr | $request '
                       '| CL=$content_length TE=$http_transfer_encoding '
                       '| host=$host';

    access_log /var/log/nginx/access.log smuggle;

    server {
        listen 8000;

        location / {
            proxy_pass http://backend:3000;

            # Important: keep HTTP/1.1 behavior explicit
            proxy_http_version 1.1;

            # Do NOT auto-close connections (needed for later phases)
            proxy_set_header Connection "";
        }
    }
}
