events {}

http {
    log_format detailed '$remote_addr - $request '
                        'Headers: $http_host $http_user_agent '
                        'CL:$content_length TE:$http_transfer_encoding';

    access_log /var/log/nginx/access.log detailed;

    server {
        listen 8080;

        location / {
            proxy_pass http://backend:3000;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}
